CREATE TABLE DATES (
	[TIME] time,
	[DATE] date,
	
	[DATETIME] datetime,
	[DATETIME2] datetime2,
	[DATETIMEOFFSET] datetimeoffset

);


ALTER TABLE DATES ADD
[SMALLDATETIME] SMALLDATETIME;
INSERT INTO DATES ([TIME], [DATE], [DATETIME], [DATETIME2], [DATETIMEOFFSET], [SMALLDATETIME]) VALUES (
	CURRENT_TIMESTAMP,
	GETDATE(),
	SYSDATETIME(),
	SYSUTCDATETIME(),
	SYSUTCDATETIME(),
	SYSDATETIMEOFFSET()

)

/*
SYSUTCDATETIME();
SYSUTCDATE();
SYSDATETIMEOFFSET();
CURRENT_TIMESTAMP
GETDATE()
*/
SELECT * FROM DATES;


SELECT ISDATE('2/2/2020')

SELECT DAY('2/21/2020')
SELECT MONTH('3/25/2020')
SELECT YEAR('2/2/2020')

SELECT DATENAME(WEEKDAY, GETDATE())
SELECT DATENAME(WEEK, GETDATE())
SELECT DATENAME(MONTH, GETDATE())


CREATE TABLE CHILDREN(
	NAME VARCHAR(255),
	DOB datetime,
	[MONTH] varchar(255),
	[DAY] varchar(255),
	[DATE] varchar(25)
);

INSERT INTO CHILDREN VALUES ('SAM' , SYSDATETIME(), DATENAME(MONTH, SYSDATETIME()), DATENAME(WEEKDAY, GETUTCDATE()), DATENAME(DAY, SYSUTCDATETIME()))
SELECT * FROM CHILDREN;
 

SELECT DATEPART(WEEKDAY,GETUTCDATE())
DECLARE @B datetime;
SET @B = DATEADD(DAY,2,SYSUTCDATETIME());

SELECT DATEDIFF(DAY,SYSUTCDATETIME(),@B)

SELECT CAST(1 AS nvarchar(1))
select convert(nvarchar,SYSUTCDATETIME(),105);

select * from tblperson;

select 
case 
	when genderid = 2 
	then 'male' 
	else 'unknown' 
end as gender from tblperson;