SELECT ID,NAME,EMAIL,GENDERID, 
COUNT(GENDERID) OVER (PARTITION BY GENDERID) AS GENDERS,
AVG(GENDERID) OVER (PARTITION BY GENDERID) AS MAXIGENDERS,
RANK() OVER ( ORDER BY GENDERID) AS RANKGENDERS ,
DENSE_RANK() OVER ( ORDER BY GENDERID) AS DENSEGENDER
 FROM TBLPERSON;

 SELECT ID, NAME , LEAD(ID) OVER (ORDER BY ID), LAG(ID) OVER (ORDER BY ID) FROM TBLPERSON;

 sp_depends tblperson;
 

 SELECT * FROM TBLPERSON;
 CREATE PROC [spEnterPerson] 'TIP TIP3', 'TIPWP@GMAIL.COM',1, 'PUNE',23,'333'
 @NAME VARCHAR(255),
 @EMAIL VARCHAR(255),
 @GENDERID VARCHAR(255),
 @CITY VARCHAR(255),
 @AGE INT,
 @HIDDENEMAIL VARCHAR(255)
 AS 
 BEGIN
	INSERT INTO TBLPERSON (NAME,EMAIL, GENDERID, CITY, AGE, HIDDENEMAIL)
	 VALUES(@NAME, @EMAIL,@GENDERID, @CITY, @AGE,NULL);
	 DECLARE @A INT ;
	 SET @A = CAST(SCOPE_IDENTITY() as int)

	EXEC spHideEmail 1,@A;
END;

CREATE TABLE MANAGERS (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(255),
	MANAGERID INT,	
);

CREATE TABLE MANAGERS2 (
	ID INT PRIMARY KEY IDENTITY(1,1),
	NAME VARCHAR(255)

)

SELECT * FROM MANAGERS2;
SELECT * FROM MANAGERS;

MERGE MANAGERS2 AS T
USING MANAGERS AS S
ON T.ID = S.ID 
WHEN MATCHED THEN 
UPDATE SET T.NAME = CONCAT(S.NAME,'T')
WHEN NOT MATCHED THEN
INSERT (NAME) VALUES (S.NAME)
WHEN NOT MATCHED  BY SOURCE THEN 
DELETE;

INSERT INTO MANAGERS2 (NAME ) VALUES ('Mike m'),('Tommy'),('Raghu'),('Monte'),('Badri'),('Sam'),('Sid')
INSERT INTO MANAGERS (NAME , MANAGERID) VALUES ('Mike', 2),('Tom',3),('Raghu',3),('Monte',2),('Badri',4),('Sam',NULL),('Sid',1)

SELECT A.ID,A.NAME,A.MANAGERID,B.NAME AS [MANAGER NAME] FROM MANAGERS A INNER JOIN MANAGERS B ON A.ID=B.MANAGERID ORDER BY A.ID;


SELECT * FROM TBLPERSON; 