CREATE TABLE TBLPERSON 
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(255),
EMAIL VARCHAR(255),
GENDERID INT
);

CREATE TABLE TBLGENDER
(
ID INT IDENTITY(1,1) PRIMARY KEY,
NAME VARCHAR(255)
);

ALTER TABLE TBLPERSON ADD CONSTRAINT 
TBLPERSON_TBLGENDER_FK 
FOREIGN KEY(GENDERID) REFERENCES TBLGENDER(ID);

ALTER TABLE TBLPERSON ALTER COLUMN GENDERID INT NULL;

ALTER TABLE TBLPERSON ADD CONSTRAINT 
DC_TBLPERSON_TBLGENDER 
DEFAULT 3 FOR GENDERID;


INSERT INTO TBLGENDER VALUES ('Male'),('Female'),('Unknown')
INSERT INTO TBLPERSON VALUES ('Akshat', 'a@gmail.com',1,4), ('Shubham', 's@gmail.com',2,6),('Akarsh', 't@gmail.com',3,10)

--- FOR DEFAULT VALUE THE COLUMNS NAME NEEDS TO BE SPECIFIED
INSERT INTO TBLPERSON (NAME, EMAIL) VALUES ('Adit', 'ad@gmail.com')


--- CASCADING REFERENCIAL INTIGRITY IF WE TRY TO DELETE DATA FROM TBLGENDER TABLE WHICH WILL GIVE ERROR AS IT IS BEING USED FOR GENDERID IN TBLPERSON
--- WE CAN DELETE IT AND SET THE VALUE TO DEFAULT OR TO NULL OR CASCADE( IT WILL DELETE THE DATA FROM OTHER TABLE WHICH ARE USING IT)
SELECT * FROM TBLPERSON;
SELECT * FROM TBLGENDER;

ALTER TABLE TBLPERSON
DROP CONSTRAINT
DC_TBLPERSON_TBLGENDER;


ALTER TABLE TBLPERSON DROP COLUMN AGE;

DBCC CHECKIDENT (TBLPERSON, RESEED, 0);

--- FOR SETTING IDENTITY INSERT 
SET IDENTITY_INSERT TBLPERSON OFF;

ALTER TABLE TBLPERSON ADD AGE INT;

DELETE FROM TBLPERSON;
INSERT INTO TBLPERSON (NAME, EMAIL ,GENDERID, AGE) VALUES ('Manav', 'manav@gmail.com',2, 31)
INSERT INTO TBLGENDER(NAME) VALUES ('TRANS')

DELETE FROM TBLGENDER WHERE ID = 4;
ALTER TABLE TBLPERSON
DROP CONSTRAINT 
CK_TBLPERSON_AGE;

ALTER TABLE TBLPERSON
ADD CONSTRAINT 
CK_TBLPERSON_AGE CHECK (AGE > 0 AND AGE < 150);

-- MOSTLY USED THIS SESSION AND SAME SCOPE
SELECT SCOPE_IDENTITY();

-- ANY SESSION AND SAME SCOPE
SELECT @@IDENTITY;


ALTER TRIGGER TR_TBLPERSON ON TBLPERSON FOR INSERT
AS
BEGIN
	SELECT * FROM TBLPERSON;
	SELECT * FROM TBLGENDER;
END;

SELECT IDENT_CURRENT('TBLPERSON');

ALTER TABLE TBLPERSON ADD CONSTRAINT
UQ_TBLPERSON_EMAIL UNIQUE(EMAIL);